export const DEFAULT_MIN_POLIPROB = 80; // was 70 in propub land

export const COMMON_TARGETS_GROUPED = {
	MinAge: [
		["MinAge", '13'],
		["MinAge", '18'],
		["MinAge", '20'],
		["MinAge", '21'],
		["MinAge", '22'],
		["MinAge", '24'],
		["MinAge", '25'],
		["MinAge", '30'],
		["MinAge", '35'],
		["MinAge", '40'],
		["MinAge", '45'],
		["MinAge", '50'],
		["MinAge", '55'],
		["MinAge", '59'],
		["MinAge", '65'] ],
	Region: [
		["LOCATION", 'the United States'],
		["LOCATION", 'California'],
		["LOCATION", 'Florida'],
		["LOCATION", 'Texas'],
		["LOCATION", 'Michigan'],
		["LOCATION", 'Washington'],
		["LOCATION", 'Colorado'],
		["LOCATION", 'New York'],
		["LOCATION", 'Ohio'],
		["LOCATION", 'Massachusetts'],
		["LOCATION", 'Minnesota'],
		["LOCATION", 'Arizona'],
		["LOCATION", 'Wisconsin'],
		["LOCATION", 'Missouri'],
		["LOCATION", 'North Carolina'],
		["LOCATION", 'Pennsylvania'],
		["LOCATION", 'Georgia'],
		["LOCATION", 'Nevada'],
		["LOCATION", 'Illinois'],
		["LOCATION", 'North Dakota'],
		["LOCATION", 'Oregon'],
		["LOCATION", 'Montana'],
		["LOCATION", 'Iowa']
	],
	"Website visits": [["CUSTOM_AUDIENCES_WEBSITE", 'visited a particular website' ]],
	List: [["CUSTOM_AUDIENCES_DATAFILE"]],
	Like: [ ["CONNECTION"] ],
	"Behaviors":[
		["BCT", 'Frequent Travelers'],
		["BCT", 'Likely engagement with US political content (liberal)'],
		["BCT", 'Likely engagement with US political content (conservative)'],
		["BCT", 'African American (US)'],
		["BCT", 'Asian American (US)'],
		["BCT", 'Hispanic (US - All)'],
		["BCT", 'Hispanic (US - English dominant)'],
		["BCT", 'Hispanic (US - Bilingual)'],
		["BCT", 'Hispanic (US - Spanish dominant)'],
		["BCT", 'Household income: top 10% of ZIP codes (US)' ],
		["BCT", 'Household income: top 10%-25% of ZIP codes (US)' ],
		],
	Gender: [ 
		["Gender", 'FEMALE' ], 
		["Gender", 'MALE' ]
		],
	Interest: [

		["INTERESTS", 'Barack Obama'],
		["INTERESTS", 'Bernie Sanders'],
		["INTERESTS", 'Donald Trump'],
		["INTERESTS", 'Planned Parenthood'],
		["INTERESTS", 'Politics and social issues'],
		["INTERESTS", 'Politics'],
		["INTERESTS", 'Republican Party (United States)'],
		["INTERESTS", 'Sean Hannity'],
		],
	Language: [ ["LOCALE", 'English (US)'] ],
};