export const COMMON_TARGETS = [
	{ filter_target: 'MinAge', filter_segment: '18' },
	{ filter_target: 'Age', filter_segment: '18 and older' },
	{ filter_target: 'Region', filter_segment: 'the United States' },
	{ filter_target: 'Refilter_targeting', filter_segment: 'people who may be similar to their customers' },
	{ filter_target: 'List', filter_segment: '' },
	{ filter_target: 'Like', filter_segment: '' },
	{ filter_target: 'Website', filter_segment: 'people who have visited their website or used one of their apps' },
	{ filter_target: 'Activity on the Facebook Family', filter_segment: '' },
	{ filter_target: 'Segment', filter_segment: 'US politics (very liberal)' },
	{ filter_target: 'MinAge', filter_segment: '25' },
	{ filter_target: 'MinAge', filter_segment: '35' },
	{ filter_target: 'Gender', filter_segment: 'women' },
	{ filter_target: 'Age', filter_segment: '25 and older' },
	{ filter_target: 'Age', filter_segment: '35 and older' },
	{ filter_target: 'MinAge', filter_segment: '30' },
	{ filter_target: 'Age', filter_segment: '30 and older' },
	{ filter_target: 'MinAge', filter_segment: '21' },
	{ filter_target: 'Age', filter_segment: '21 and older' },
	{ filter_target: 'State', filter_segment: 'California' },
	{ filter_target: 'Region', filter_segment: 'California' },
	{ filter_target: 'MinAge', filter_segment: '45' },
	{ filter_target: 'Region', filter_segment: 'Florida' },
	{ filter_target: 'Age', filter_segment: '45 and older' },
	{ filter_target: 'Region', filter_segment: 'Texas' },
	{ filter_target: 'MinAge', filter_segment: '40' },
	{ filter_target: 'Age', filter_segment: '40 and older' },
	{ filter_target: 'Segment', filter_segment: 'US politics (liberal)' },
	{ filter_target: 'Gender', filter_segment: 'men' },
	{ filter_target: 'MinAge', filter_segment: '50' },
	{ filter_target: 'Interest', filter_segment: 'Democratic Party (United States)' },
	{ filter_target: 'Age', filter_segment: '50 and older' },
	{ filter_target: 'State', filter_segment: 'New York' },
	{ filter_target: 'State', filter_segment: 'Texas' },
	{ filter_target: 'MinAge', filter_segment: '55' },
	{ filter_target: 'State', filter_segment: 'Florida' },
	{ filter_target: 'Interest', filter_segment: 'Barack Obama' },
	{ filter_target: 'Region', filter_segment: 'Michigan' },
	{ filter_target: 'Region', filter_segment: 'Washington' },
	{ filter_target: 'Age', filter_segment: '55 and older' },
	{ filter_target: 'Region', filter_segment: 'Colorado' },
	{ filter_target: 'Segment', filter_segment: 'US politics (moderate)' },
	{ filter_target: 'Region', filter_segment: 'New York' },
	{ filter_target: 'Interest', filter_segment: 'Bernie Sanders' },
	{ filter_target: 'Region', filter_segment: 'Ohio' },
	{ filter_target: 'Region', filter_segment: 'Massachusetts' },
	{ filter_target: 'Region', filter_segment: 'Minnesota' },
	{ filter_target: 'Refilter_targeting', filter_segment: 'recently near their business' },
	{ filter_target: 'State', filter_segment: 'Washington' },
	{ filter_target: 'Segment', filter_segment: 'US politics (very conservative)' },
	{ filter_target: 'Region', filter_segment: 'Arizona' },
	{ filter_target: 'State', filter_segment: 'Minnesota' },
	{ filter_target: 'State', filter_segment: 'Illinois' },
	{ filter_target: 'Age', filter_segment: '13 and older' },
	{ filter_target: 'MinAge', filter_segment: '24' },
	{ filter_target: 'MinAge', filter_segment: '13' },
	{ filter_target: 'State', filter_segment: 'Michigan' },
	{ filter_target: 'City', filter_segment: 'New York' },
	{ filter_target: 'Region', filter_segment: 'Wisconsin' },
	{ filter_target: 'State', filter_segment: 'Pennsylvania' },
	{ filter_target: 'Region', filter_segment: 'Missouri' },
	{ filter_target: 'City', filter_segment: 'Washington' },
	{ filter_target: 'Region', filter_segment: 'North Carolina' },
	{ filter_target: 'Interest', filter_segment: 'Donald Trump' },
	{ filter_target: 'Region', filter_segment: 'Pennsylvania' },
	{ filter_target: 'Age', filter_segment: '24 and older' },
	{ filter_target: 'MaxAge', filter_segment: '54' },
	{ filter_target: 'MaxAge', filter_segment: '49' },
	{ filter_target: 'BCT', filter_segment: 'Member of a family-based household.' },
	{ filter_target: 'MinAge', filter_segment: '22' },
	{ filter_target: 'State', filter_segment: 'Virginia' },
	{ filter_target: 'Interest', filter_segment: 'Planned Parenthood' },
	{ filter_target: 'Region', filter_segment: 'Georgia' },
	{ filter_target: 'Region', filter_segment: 'Nevada' },
	{ filter_target: 'BCT', filter_segment: 'US politics (conservative)' },
	{ filter_target: 'Age', filter_segment: '22 and older' },
	{ filter_target: 'State', filter_segment: 'District of Columbia' },
	{ filter_target: 'Interest', filter_segment: 'Politics and social issues' },
	{ filter_target: 'State', filter_segment: 'Maryland' },
	{ filter_target: 'Region', filter_segment: 'Illinois' },
	{ filter_target: 'MaxAge', filter_segment: '64' },
	{ filter_target: 'Region', filter_segment: 'North Dakota' },
	{ filter_target: 'State', filter_segment: 'North Carolina' },
	{ filter_target: 'State', filter_segment: 'Missouri' },
	{ filter_target: 'State', filter_segment: 'Ohio' },
	{ filter_target: 'Region', filter_segment: 'Oregon' },
	{ filter_target: 'Region', filter_segment: 'Montana' },
	{ filter_target: 'State', filter_segment: 'Arizona' },
	{ filter_target: 'BCT', filter_segment: 'Likely engagement with US political content (liberal)' },
	{ filter_target: 'Age', filter_segment: '65' },
	{ filter_target: 'MinAge', filter_segment: '65' },
	{ filter_target: 'MaxAge', filter_segment: '65' },
	{ filter_target: 'Language', filter_segment: 'English (US)' },
	{ filter_target: 'Interest', filter_segment: 'Politics' },
	{ filter_target: 'Interest', filter_segment: 'Republican Party (United States)' },
	{ filter_target: 'MaxAge', filter_segment: '55' },
	{ filter_target: 'BCT', filter_segment: 'African American (US).' },
	{ filter_target: 'Region', filter_segment: 'Iowa' },
	{ filter_target: 'MinAge', filter_segment: '20' },
	{ filter_target: 'MaxAge', filter_segment: '34' },
	{ filter_target: 'State', filter_segment: 'Oregon' },
];

export const COMMON_TARGETS_GROUPED = {
	MinAge: [
		'13',
		'18',
		'20',
		'21',
		'22',
		'24',
		'25',
		'30',
		'35',
		'40',
		'45',
		'50',
		'55',
		'59',
		'65' ],
	Region: [
		'the United States',
		'California',
		'Florida',
		'Texas',
		'Michigan',
		'Washington',
		'Colorado',
		'New York',
		'Ohio',
		'Massachusetts',
		'Minnesota',
		'Arizona',
		'Wisconsin',
		'Missouri',
		'North Carolina',
		'Pennsylvania',
		'Georgia',
		'Nevada',
		'Illinois',
		'North Dakota',
		'Oregon',
		'Montana',
		'Iowa' ],
	Retargeting: [
		'people who may be similar to their customers',
		'recently near their business' ],
	List: [ '' ],
	Like: [ '' ],
	Website: [ 'people who have visited their website or used one of their apps' ],
	'Activity on the Facebook Family': [ '' ],
	BCT:[
		'Member of a family-based household.',
		'Likely engagement with US political content (liberal)',
		'Likely engagement with US political content (conservative)',
		'African American (US)',
		'Asian American (US)',
		'Hispanic (US - All)',
		'Hispanic (US - English dominant)',
		'Hispanic (US - Bilingual)',
		'Hispanic (US - Spanish dominant)'],
	Gender: [ 'female', 'male' ],
	Interest: [
		'Democratic Party (United States)',
		'Barack Obama',
		'Bernie Sanders',
		'Donald Trump',
		'Planned Parenthood',
		'Politics and social issues',
		'Politics',
		'Republican Party (United States)',
		'Sean Hannity', 
		'US politics (very liberal)',
		'US politics (liberal)',
		'US politics (moderate)',
		'US politics (conservative)',
		'US politics (very conservative)',

		],
	Language: [ 'English (US)' ],
};